import Head from "next/head";
import SideMenu from "../SideMenu/page";
import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import "react-toastify/dist/ReactToastify.css"
import { useAuth } from "@/utils/auth";
import { toast } from "react-toastify";



const Layout = ({ children }) => {
    const router = useRouter();
    // const { isAdmin } = useAuth();
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const timer = setTimeout(() => {
          setIsLoading(false);
        }, 3000); // Set the timeout to 1 minute (60000 milliseconds)
    
        return () => clearTimeout(timer);
      }, []);

      if (isLoading) {
        return (
          <div className="flex justify-center items-center h-screen">
            <div className="animate-spin rounded-full h-20 w-20 border-t-2 border-b-2 border-gray-900"></div>
          </div>
        );
      }
    
     
    return (
        <div>
            <Head>
                <title>Trackage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SideMenu />
            <main className="flex flex-1">{children}</main>
        </div>
);
};

export default Layout;
