import { Inter } from "next/font/google";
import Head from "next/head";
import LandingPage from "./home";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
      <div>
        <Head>
        <title>Trackage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
        <LandingPage/>
      </div>
          
    );
  }





